import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Search from "@/components/Home/Search";
import Title from "@/components/Home/Title";
import Info from "@/components/Home/Info";

export default function Home() {
  return (
    <>
      <Head>
        <title>CANLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Title />
        <Search />
        <Info />
      </main>
    </>
  );
}
