import Head from "next/head";
import Search from "@/components/Home/Search";
import Title from "@/components/Home/Title";
import Info from "@/components/Home/Info";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>롤챔 | CANLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6130554803659144"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <Wrapper>
        <Title />
        <Search />
        <Info />
      </Wrapper>
    </>
  );
}

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  max-width: ${({ theme }) => theme.WIDTH.pc};
  min-height: 100vh;
  margin: auto;
  padding: 6rem;

  &::after {
    content: "";
    background: url(/assets/img/champion/centered/Varus_7.jpg) no-repeat center center;
    background-size: cover;
    opacity: 0.5;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
  }
`;
